wowlinks:
  "aapl": "https://www.apple.com"
  "amzn": "https://amazon.com"
  "msft": "https://onedrive.live.com"
  "gh": "https://github.com"
  "goo": "https://google.com"
  "wow": "https://github.com/wowlink"
  "q": "https://www.quora.com"
  "rktn-card": "https://rakutencard.syf.com/login"
  "yt": "https://www.youtube.com"
  "mdum": "https://medium.com"
