wowlinks:
  "amzn": "https://amazon.com"
  "msft": "https://onedrive.live.com"
  "gh": "https://github.com"
  "goo": "https://google.com"
  "wow": "https://github.com/wowlink"
  "q": "https://www.quora.com"
